enabled_news: ["en"]
news:
  news_host: "http://news.railstutorial.org"
home:
  home_railstutorial: "https://www.railstutorial.org/"
  home_sign_up: "http://localhost:3000/signup"
help:
  help_help: "http://www.railstutorial.org/help"
  help_book: "http://www.railstutorial.org/book"
footer:
  footer_rubyturorial: "http://www.railstutorial.org/"
  footer_name: "http://www.michaelhartl.com/"
user:
  name:
    maximum: 50
    maximum: 255
  password:
    minimum: 6
users_helper:
  user_size: 80
  image_size: "75x80"
header:
  header_login: "http://localhost:3000/login"
users:
  edit:
    change_avatar: "http://gravatar.com/emails"
users_controller:
  page_number: 6
